name: 3D_GNNs
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - cpuonly=2.0
  - cryptography=38.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - greenlet=1.1.1
  - icu=70.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter_client=7.3.5
  - jupyter_core=4.11.2
  - jupyter_server=1.18.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.4.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.5.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openh264=2.1.1
  - openssl=1.1.1s
  - pandas=1.4.4
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycairo=1.21.0
  - pygments=2.11.2
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytorch=1.13.0
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyzmq=23.2.0
  - rdkit=2022.03.2
  - readline=8.2
  - reportlab=3.5.67
  - requests=2.28.1
  - send2trash=1.8.0
  - setuptools=65.5.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=1.4.39
  - sqlite=3.39.3
  - stack_data=0.2.0
  - sympy=1.11.1
  - terminado=0.13.1
  - testpath=0.6.0
  - tk=8.6.12
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tornado=6.2
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022f
  - urllib3=1.26.12
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - charset-normalizer==2.0.4
    - cycler==0.11.0
    - fire==0.5.0
    - fonttools==4.25.0
    - joblib==1.2.0
    - morfeus-ml==0.7.2
    - mpmath==1.2.1
    - munkres==1.1.4
    - packaging==21.3
    - pycparser==2.21
    - pyopenssl==22.0.0
    - python-dateutil==2.8.2
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - six==1.16.0
    - termcolor==2.2.0
    - threadpoolctl==3.1.0
    - torch-cluster==1.6.0
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.0.9
    - torch-sparse==0.6.15
    - torch-spline-conv==1.2.1
    - tqdm==4.64.1
    - wheel==0.37.1